WholesaleHunter/Models/MyOrderHistory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WholesaleHunter.Models
{
    public class MyOrderHistory
    {
        public int ProductID { get; set; }

        public string ItemTitle { get; set; }

        public string ItemDescriptionShort { get; set; }

        public string Thumbnail { get; set; }

        public DateTime OrderDate { get; set; }

        public int Quantity { get; set; }

        public string OrderStatus { get; set; }

        public string TrackingNumber { get; set; }

        public string Carrier { get; set; }

        public double Price { get; set; }


    }
}

WholesaleHunter/Models/MyPassword.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WholesaleHunter.Models
{
    public class MyPassword
    {
        public string Password1 { get; set; }

        public string Password2 { get; set; }

        public string Password3 { get; set; }

        public int CustomerID { get; set; }
    }
}

WholesaleHunter/Models/MyPaymentMethod.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WholesaleHunter.Models
{
    public class MyPaymentMethod
    {
        public int CustomerPaymentMethodID { get; set; }

        public int CustomerID { get; set; }

        public string LastFour { get; set; }

        public string AuthorizeNETToken { get; set; }

        public DateTime ExpirationDate { get; set; }

        public bool IsPrimary { get; set; }

        public string BillAddr1 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillZIP { get; set; }

        //These are not stored anywhere on this site.  They are sent to Authorize.net
        public string PaymentMethodNumber { get; set; }

        public string PaymentMethodCVV { get; set; }

        public string BillingZipCode { get; set; }


        //Used to construct Expiration Date
        public string ExpirationMonth { get; set; }

        public string ExpirationYear { get; set; }

    }
}

WholesaleHunter/Models/RecentlyViewed.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WholesaleHunter.Models
{
    public class RecentlyViewed
    {
        public string ItemTitle { get; set; }

        public string LinkTarget { get; set; }

        public string ImageLocation { get; set; }

        public string ImageDescriptionShort { get; set; }

        public decimal Price { get; set; }

    }
}

WholesaleHunter/ViewModels/MyAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WholesaleHunter.Models;

namespace WholesaleHunter.ViewModels
{
    public class MyAccountViewModel : BaseViewModel
    {
        public List<MyAddress> CustomerAddress { get; set; }

        public MyAddress NewCustomerAddress { get; set; }

        public List<MyPaymentMethod> CustomerPaymentMethod { get; set; }

        public MyPaymentMethod NewCustomerPaymentMethod { get; set; }

        public List<MyOrderHistory> MyOrderHistory { get; set; }

        public bool HasOrderHistory { get; set; }

        public List<RecentlyViewed> RecentlyViewed { get; set; }

        public string Phone { get; set; }

        public string EMail { get; set; }

        public bool GetNewsletter { get; set; }

        public string OrderScrollUrl { get; set; }

        public int SelectedTab { get; set; }

        public MyInfo MyInfo { get; set; }
    }
}

WholesaleHunter/Controllers/MyAccountController.cs
using Dapper;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WholesaleHunter.Classes;
using WholesaleHunter.Models;
using WholesaleHunter.ViewModels;


namespace WholesaleHunter.Controllers
{
    [OutputCache(Duration = 1)]
    [Authorize]
    public class MyAccountController : Controller
    {
        public AppUserState appuser;
        private string dbname = "WholesaleHunterCom";



        // GET: MyAccount
        public ActionResult Index(MyAccountSelectedTab sTab)
        {

            MyAccountViewModel vm = new MyAccountViewModel();
            vm.SelectedTab = sTab.SelectedTab;
            if (getClaims())
            {
                vm.CustomerID = this.appuser.UserID;
                vm.CustomerEmail = this.appuser.Email;
            }
            else
            {
                vm.CustomerID = 0;
                vm.CustomerEmail = "";
            }

            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings[dbname].ConnectionString))
            {
                var p = new DynamicParameters();
                p.Add("@CustomerID", vm.CustomerID);
                vm.MyInfo = db.Query<MyInfo>("WholesaleHunterCom.sMyInfo", p, commandType: CommandType.StoredProcedure).Single<MyInfo>();
            }

            ViewBag.CustomerID = vm.CustomerID;
            return View(vm);
        }

        public ActionResult MyAddresses(int userID)
        {
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings[dbname].ConnectionString))
            {
                MyAccountViewModel vm = new MyAccountViewModel();

                //Get My Addresses
                var pMA = new DynamicParameters();
                pMA.Add("@CustomerID", userID);
                vm.CustomerAddress = db.Query<MyAddress>("WholesaleHunterCom.sMyAddresses", pMA, commandType: CommandType.StoredProcedure).ToList<MyAddress>();
                ViewBag.CustomerID = userID;
                return View(vm);
            }

        }

        public ActionResult MyPaymentMethods(int userID)
        {
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings[dbname].ConnectionString))
            {
                MyAccountViewModel vm = new MyAccountViewModel();

                //Get My Addresses
                var pMA = new DynamicParameters();
                pMA.Add("@CustomerID", userID);
                vm.CustomerPaymentMethod = db.Query<MyPaymentMethod>("WholesaleHunterCom.sMyPaymentMethods", pMA, commandType: CommandType.StoredProcedure).ToList<MyPaymentMethod>();
                ViewBag.CustomerID = userID;
                return View(vm);
            }

        }

        public ActionResult MyContactPreferences(int userID)
        {
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings[dbname].ConnectionString))
            {
                MyAccountViewModel vm = new MyAccountViewModel();

                //Get My Contact Preferences
                var pMCP = new DynamicParameters();
                pMCP.Add("@CustomerID", userID);

                Customer customer = db.Query<Customer>("WholesaleHunterCom.sMyContactPreferences", pMCP, commandType: CommandType.StoredProcedure).FirstOrDefault();
                vm.Phone = customer.Phone;
                vm.EMail = customer.EMail;
                vm.GetNewsletter = customer.GetNewsletter;
                vm.CustomerID = userID;

                ViewBag.CustomerID = userID;

                return View(vm);
            }
        }

        public ActionResult MyPassword(int userID)
        {
            ViewBag.CustomerID = userID;
            return View();
        }

        public ActionResult MyOrderHistory(int userID, int startRow = 1, int EndRow = 15)
        {
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings[dbname].ConnectionString))
            {
                MyAccountViewModel vm = new MyAccountViewModel();

                //Get My Addresses
                var pOH = new DynamicParameters();
                pOH.Add("@CustomerID", userID);
                pOH.Add("@StartRow", startRow);
                pOH.Add("@EndRow", EndRow);
                vm.MyOrderHistory = db.Query<MyOrderHistory>("WholesaleHunterCom.sMyOrders", pOH, commandType: CommandType.StoredProcedure).ToList<MyOrderHistory>();
                ViewBag.CustomerID = userID;

                if (vm.MyOrderHistory.Count > 0)
                {
                    //Build the scrolling url for the next group of orders
                    MyOrdersScroll myOrdersScroll = new MyOrdersScroll();
                    myOrdersScroll.StartNum = startRow;
                    myOrdersScroll.EndNum = EndRow;
                    vm.OrderScrollUrl = buildNextOrderScrollingURL(userID, myOrdersScroll);
                    vm.HasOrderHistory = true;
                }
                else
                {
                    vm.OrderScrollUrl = string.Empty;
                    if (startRow == 1)
                    {
                        vm.HasOrderHistory = false;
                    }
                    else
                    {
                        vm.HasOrderHistory = true;
                    }
                }
                return View(vm);
            }
        }

        private string buildNextOrderScrollingURL(int UserID, MyOrdersScroll data)
        {
            int newStartRow = data.EndNum + 1;
            int newEndRow = newStartRow + 15;
            StringBuilder url = new StringBuilder();
            string hostname = ConfigurationManager.AppSettings["Host"].ToString();
            if (!hostname.EndsWith("/"))
            {
                hostname = hostname + "/";
            }
            url.Append(hostname);
            url.Append("MyAccount/MyOrderHistory?UserID=");
            url.Append(UserID);
            url.Append("&StartRow=");
            url.Append(newStartRow);
            url.Append("&EndRow=");
            url.Append(newEndRow);


            return url.ToString();

        }

        public ActionResult RecentlyViewed(int userID, int startRow = 1, int endRow = 5)
        {
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings[dbname].ConnectionString))
            {
                MyAccountViewModel vm = new MyAccountViewModel();

                //Get My Contact Preferences
                var pRV = new DynamicParameters();
                pRV.Add("@CustomerID", userID);
                pRV.Add("@StartRow", startRow);
                pRV.Add("@EndRow", endRow);

                vm.RecentlyViewed = db.Query<RecentlyViewed>("WholesaleHunterCom.sRecentlyViewed", pRV, commandType: CommandType.StoredProcedure).ToList<RecentlyViewed>();

                ViewBag.CustomerID = userID;

                return View(vm);
            }
        }

        public ActionResult MyAccountLogout()
        {
            MyAccountViewModel vm = new MyAccountViewModel();
            getClaims();
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings[dbname].ConnectionString))
            {
                //Get My Contact Preferences
                var pRV = new DynamicParameters();
                pRV.Add("@CustomerID", appuser.UserID);

                vm.MyInfo = db.Query<MyInfo>("WholesaleHunterCom.sMyInfo", pRV, commandType: CommandType.StoredProcedure).FirstOrDefault();

                ViewBag.CustomerID = appuser.UserID;
            }

            return View(vm);
        }

        //public ActionResult MyAccountLogOff()
        //{
        //    IdentitySignout();
        //    return RedirectToAction("Index","Home");

        //}


        public void IdentitySignout()
        {
            var ctx = Request.GetOwinContext();
            var AuthenticationManager = ctx.Authentication;
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie,
                DefaultAuthenticationTypes.ExternalCookie);
        }
        private bool getClaims()
        {
            bool status;
            try
            {
                this.appuser = new AppUserState();
                var identity = (ClaimsIdentity)User.Identity;
                IEnumerable<Claim> claims = identity.Claims;
                foreach (Claim claim in claims)
                {
                    if (claim.Type == "userState")
                    {
                        if (!appuser.FromString(claim.Value))
                        {
                            return false;
                        }
                    }
                }
                ViewBag.email = appuser.Email;
                ViewBag.username = appuser.Email;
                ViewBag.userid = appuser.UserID;
                ViewBag.customerid = appuser.UserID;
                status = true;
            }
            catch
            {
                ViewBag.email = "";
                ViewBag.username = "";
                ViewBag.userid = "";
                ViewBag.customerid = "";
                status = false;
            }
            return status;
        }
    }
}

WholesaleHunter/Views/MyAccount/Index.cshtml
@model WholesaleHunter.ViewModels.MyAccountViewModel
@using WholesaleHunter.Models

@{
    Layout = null;
    string selectedOrderHistory = string.Empty;
    string selectedMyAddresses = string.Empty;
    string selectedPaymentMethods = string.Empty;
    string selectedContactPreferences = string.Empty;
    string selectedChangePassword = string.Empty;
    string attrChecked = "checked=\"checked\"";

    switch(Model.SelectedTab)
    {
        case 1:
            selectedMyAddresses = attrChecked;
            break;
        case 2:
            selectedPaymentMethods = attrChecked;
            break;
        case 3:
            selectedContactPreferences = attrChecked;
            break;
        case 4:
            selectedChangePassword = attrChecked;
            break;
        default:
            selectedOrderHistory = attrChecked;
            break;
    }
}

<div id="helpMask" class="helpMask">&nbsp;</div>
<table class="myAccountContainer login_table">
    <tr>
        <td colspan="2" align="center" valign="middle" style="font-size: 36px">
            <table class="myAccountHeading" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td width="10%">&nbsp;</td>
                    <td width="80%" align="center">MY ACCOUNT</td>
                    <td width="10%" align="right" valign="top">
                        <span onclick="hideMyAccount();" style="color: #00331B;font-size:14px;">close [X]</span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td height="500" colspan="2" align="left" valign="top">
            <div class="tabordion">

                <section id="orderHistory">
                    <input type="radio" name="sections" id="option" @selectedOrderHistory>
                    <label for="option">ORDER HISTORY</label>

                    <article class="MyAccountSection scrollable">
                        <div class="scroll" style="height:500px;">
                            @{
                                Html.RenderAction("MyOrderHistory", "MyAccount", new { userID = ViewBag.UserID });
                            }
                        </div>
                    </article>
                </section>

                <section id="myAddresses">
                    <input type="radio" name="sections" id="option2" @selectedMyAddresses >
                    <label for="option2">MY ADDRESSES</label>
                    <article class="MyAccountSection scrollable">
                        <div class="scroll" style="height:500px;">
                            @{
                                Html.RenderAction("MyAddresses", "MyAccount", new { userID = ViewBag.UserID });
                            }
                        </div>
                    </article>
                </section>

                <section id="myPaymentMethods">
                    <input type="radio" name="sections" id="option3" @selectedPaymentMethods>
                    <label for="option3">PAYMENT METHODS</label>
                    <article>
                        @{
        Html.RenderAction("MyPaymentMethods", "MyAccount", new { userID = ViewBag.UserID });
    }
                    </article>
                </section>

                <section id="myContactPreferences">
                    <input type="radio" name="sections" id="option4" @selectedContactPreferences>
                    <label for="option4">CONTACT PREFERENCES</label>
                    <article>
                        @{
        Html.RenderAction("MyContactPreferences", "MyAccount", new { userID = ViewBag.UserID });
    }
                    </article>
                </section>

                <section id="changePassword">
                    <input type="radio" name="sections" id="option5" @selectedChangePassword>
                    <label for="option5">CHANGE MY PASSWORD</label>
                    <article>
                        @{
                            Html.RenderAction("MyPassword", "MyAccount", new { userID = ViewBag.UserID, StartRow = ViewBag.StartRow, EndRow = ViewBag.EndRow });
                        }
                    </article>
                </section>

                <section id="logout">
                    <input type="radio" name="sections" id="option6">
                    <label for="option6">LOGOUT</label>
                    <article>
                        <div>
                            @{
                                Html.RenderAction("MyAccountLogout", "MyAccount");
                            }
                        </div>
                    </article>
                </section>

            </div>
        </td>
    </tr>
    <tr>
        <td width="241" height="15" align="center" valign="middle" bgcolor="#331709" style="color: #FFF">RECENTLY VIEWED</td>
        <td width="869">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2">
            @{
                Html.RenderAction("RecentlyViewed", "MyAccount", new { userID = ViewBag.UserID });
            }
        </td>
    </tr>
</table>
<input type="hidden" id="pwEmail" value="@Model.MyInfo.Email" />
<input type="hidden" id="pwFirstName" value="@Model.MyInfo.FirstName" />
<input type="hidden" id="pwLastName" value="@Model.MyInfo.LastName" />

WholesaleHunter/Views/MyAccount/MyAccountLogout.cshtml
@model WholesaleHunter.ViewModels.MyAccountViewModel
@{
    Layout = null;
    string template = "Email/Username: {0}<br />{1}&nbsp;{2}<br />{3}<br />{4}{5},&nbsp;{6}&nbsp;{7}<br />Phone: {8}";
    string Address2="";
    if(Model.MyInfo.Address2 != string.Empty)
    {
        Address2 = Model.MyInfo.Address2 + "<br />";
    }
    string userinfo = string.Format(template, Model.MyInfo.Email, Model.MyInfo.FirstName, Model.MyInfo.LastName, Model.MyInfo.Address1, Address2, Model.MyInfo.City, Model.MyInfo.State, Model.MyInfo.ZipCode, Model.MyInfo.Phone);
}
<script src="~/Scripts/MyAccountLogout.js"></script>

<script type="text/javascript">
        var logoutURL = ''
</script>
<br />
@if (Model.MyInfo.Email == null)
{
    @Html.Raw("Username: Guest User")
}
else
{
    @Html.Raw(userinfo)
}
<h1>Are you sure you want to logout?</h1>
<button class="myAccountButton" onclick="logoutUser()" style="float:left;" >YES</button>
<br /><br />

WholesaleHunter/Views/MyAccount/MyContactPreferences.cshtml
@model WholesaleHunter.ViewModels.MyAccountViewModel
@using WholesaleHunter.Models

@{
    Layout = null;
}

<script src="~/Scripts/MyContactPreferences.js"></script>

<input id="customerID" type="hidden" value=@ViewBag.CustomerID />

<table class="MyAccountTable">
    <tr>
        <td ><p class="contactLabel">Primary Phone</p> </td>
        <td><input type="tel" class="contactField myAccountInput" name="phone" id="phone" placeholder="Phone Number" value="@Model.Phone"></td>
    </tr>
    <tr>
        <td><p class="contactLabel">Primary Email</p> </td>
        <td><input type="email" class="contactField myAccountInput" name="email" id="email" placeholder="Email" value=@Model.EMail></td>
    </tr>
    <tr>
        <td colspan="2"><input type="checkbox" id="newsletter" name="keep" checked=@Model.GetNewsletter><small style="font-size: 12px">RECEIVE OUR NEWSLETTER</small></td>
    </tr>
    <tr>
        <td colspan="2"><button class="myAccountButton" onclick="updateContactPreferences()">SAVE</button></td>
    </tr>
</table>

WholesaleHunter/Views/MyAccount/MyOrderHistory.cshtml
@model WholesaleHunter.ViewModels.MyAccountViewModel
@using WholesaleHunter.Models
@using WholesaleHunter.Classes;

@{
    Layout = null;
}

<script src="~/Scripts/MyOrderHistory.js"></script>


<input id="customerID" type="hidden" value=@ViewBag.CustomerID />

@{ 
    int divCounter = 1;
    string trackPackage = ""; //Variable to hold constructed Tracking URL
    TrackingURL trackingURL = new TrackingURL();
}

@if(Model.HasOrderHistory) { 
    <table class="MyAccountTable">
        @foreach (var item in Model.MyOrderHistory)
        {
            //Construct the Tracking URL
            trackPackage = trackingURL.GetTrackingURL(@item.Carrier);
            trackPackage = trackPackage + @item.TrackingNumber;

            <tr>
                <td>
                    <img src="@item.Thumbnail" alt="@item.ItemTitle"/>
                </td>
                <td>
                    <div class="myOrdersTitle">
                        @item.ItemTitle
                    </div>
                    <div class="myOrderDescription">
                        @item.ItemDescriptionShort
                    </div>
                </td>
                <td>
                    @if(
                        (item.Carrier != null) &&
                        (item.Carrier.ToUpper() == "UPS" || item.Carrier.ToUpper() == "USPS") &&
                        (item.TrackingNumber != null))
                    {
                            <a href="@trackPackage" target="_blank">
                                <input id="trackShipment" class="myOrderButton" type="button" value="Track Shipment" />
                            </a>
                    }
                    <div>
                        <input id="orderAgain" class="myOrderButton" type="button" value="Order Again" onclick="buyAgain(@ViewBag.CustomerID,@item.ProductID,@item.Price,@item.Quantity)" />
                    </div>
                    <div class="myOrderDescription">@item.OrderDate.ToShortDateString()</div>
                    <div class="myOrderDescription">Ordered: @item.Quantity</div>
                    <div class="myOrderDescription">@item.OrderStatus</div>
                </td>
            </tr>
            <tr>
                <td height="13" colspan="3">
                    <hr align="left" width="100%" style="color:#D7D2B7; background-color:#D7D2B7; height:10px; border:none;">
                </td>
            </tr>

            divCounter++; //increment the counter
        }

    </table>
}
else
{
    @Html.Raw("<br /><br />No previous orders found.<br /><hr style=\"width:550px\" />");
}
@if (Model.OrderScrollUrl != string.Empty) {
    <a class="scroll" href="@Model.OrderScrollUrl">Click to see more completed orders.<br /><br /></a>
}
else
{
<span style="font-weight:bold;color:#00331b;">You are at the end of your Order History!</span>
}

WholesaleHunter/Views/MyAccount/MyPassword.cshtml
@{
    Layout = null;
}

<script src="~/Scripts/MyPassword.js"></script>

<table width="600" align="left" cellpadding="0" cellspacing="0" class="login_table">
    <tr>
        <td><p class="contactLabel">Current Password </p></td>
        <td><p class="contactField"><input type="password" name="oldpassword"  id="password1" placeholder="Current Password"></p></td>
    </tr>
    <tr>
        <td><p class="contactLabel">New Password</p> </td>
        <td><p class="contactField"><input type="password"  name="newpassword" id="password2" placeholder="New Password"></p></td>
    </tr>
    <tr>
        <td>
            <p class="contactLabel">
            Verify New Password
            </p>
        </td>
        <td>
            <p class="contactField">
            <input type="password" name="password3" id="password3" placeholder="Verify Password">
            </p>
        </td>
    </tr>
    <tr>
        <td colspan="2"><button class="myAccountButton" onclick="updatePassword()">SAVE</button></td>
    </tr>
</table>

WholesaleHunter/Views/MyAccount/MyPaymentMethods.cshtml
@model WholesaleHunter.ViewModels.MyAccountViewModel
@using WholesaleHunter.Models

@{
    Layout = null;
}

<script src="~/Scripts/MyPaymentMethods.js"></script>

<input id="customerID" type="hidden" value=@ViewBag.CustomerID />

@{ 
    int divCounter = 1;
    string myPaymentMethodID = "";
    DateTime currentDate = DateTime.Now.Date;  //Get today's date for comparison against expiration
    int currentYear = currentDate.Year; //starting point for year drop down when adding new credit card
    int finalYear = currentYear + 15;  //end point for year drop down when adding new credit card
    int yearCounter = 1; //counter for creating year dropdown list
}

<table class="MyAccountTable">
    @foreach(var item in Model.CustomerPaymentMethod)
    {
        myPaymentMethodID = "myPaymentMethodIDVal" + divCounter;
        <tr>
            <td>
                <div>
                    Card ending in @item.LastFour
                    @Html.HiddenFor(model => item.CustomerPaymentMethodID, new { id=@myPaymentMethodID})
                    @if(item.ExpirationDate < @currentDate)
                    {
                    <p class="expiredCard"> Expired  </p>
                    }
                </div>
            </td>
            <td>
                @if (item.IsPrimary == true)
                {
                    <div class="primaryAddress">
                        Primary
                    </div>
                }
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="button" class="myAccountButton" value="Delete" onclick="deletePaymentMethod(@divCounter)" id="deletePaymentMethod" />
                @if (item.IsPrimary != true)
                {
                    <input type="button" class="myAccountButton" value="Make Primary" onclick="makePrimaryPaymentMethod(@divCounter)" />
                }
            </td>
        </tr>
        <tr>
            <td height="13" colspan="2">
                <hr align="left" width="100%" style="color:#D7D2B7; background-color:#D7D2B7; height:10px; border:none;">
            </td>
        </tr>
        divCounter++;
    }
    @if(divCounter==1)
    {
        @Html.Raw("<br /><br /><br />You have no payment methods saved.<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />")
    }
    <!--
    <tr>
        <td></td>
        <td>
            <input type="button" class="myAccountButton" value="Add New" onclick="showNewPaymentMethod()" id="addNew" />
        </td>
    </tr>

    <tr>
        <td id="newPaymentMethod" class="addNewPaymentMethod">
            <table>
                <tr>
                    <td>
                        Card Number
                    </td>
                    <td>
                        <input id="newCardNumber" class="myAccountInput" type="text" placeholder="Card Number" />
                    </td>
                </tr>
                <tr>
                    <td>
                        Expiration
                    </td>
                    <td>
                        <select size="1" class="select selectStyle paymentMethodMonth" id="newExpirationMonth" name="ExpirationMonth">
                            <option selected=selected>Month</option>
                            <option value="0">January</option>
                            <option value="1">February</option>
                            <option value="2">March</option>
                            <option value="3">April</option>
                            <option value="4">May</option>
                            <option value="5">June</option>
                            <option value="6">July</option>
                            <option value="7">August</option>
                            <option value="8">September</option>
                            <option value="9">October</option>
                            <option value="10">November</option>
                            <option value="11">December</option>
                        </select>
                        <select size="1" class="select selectStyle paymentMethodYear" id="newExpirationYear">
                            <option selected=selected>Year</option>
                            @*
                            @for (yearCounter = currentYear; yearCounter <= finalYear; yearCounter++)
                            {
                                <option value=@yearCounter>@yearCounter</option>
                            } *@
                        </select>
                        <input id="newExpirationYear" type="text" placeholder="Year" class="paymentMethodYear" />
                    </td>
                </tr>
                <tr>
                    <td>
                        CVV
                    </td>
                    <td>
                        <input type="text" id="newCVV" class="paymentMethodCVV myAccountInput" placeholder="CVV" />
                    </td>
                </tr>
                <tr>
                    <td>
                        Billing Zip Code
                    </td>
                    <td>
                        <input type="text" id="newBillingZipCode" class="paymentMethodCVV myAccountInput" placeholder="ZIP Code" />
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="button" class="myAccountButton" value="Save" onclick="addPaymentMethod()" id="newPaymentMethod" />
                        <input type="button" class="myAccountButton" value="Cancel" onclick="showNormal()" id="cancelNewPaymentMethod" />
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    -->
</table>

WholesaleHunter/Views/MyAccount/RecentlyViewed.cshtml
@model WholesaleHunter.ViewModels.MyAccountViewModel
@using WholesaleHunter.Models

@{
    Layout = null;
}

<table class="recentlyViewedTable">
    <tr>
        @foreach(var item in Model.RecentlyViewed)
        {            
            <td class="recentlyViewedPic">
                <a href="/Product/Details/@item.LinkTarget">
                    <img src="@item.ImageLocation" alt="Link to @item.ItemTitle"/>
                </a>
                
            </td>

            <td class="RecentlyViewedInfo">
                <a href="/Product/Details/@item.LinkTarget" class="RecentlyViewedInfo">
                    <div style="font-weight:bold;color:black;font-size:14px;">@item.ItemTitle</div>
                    <!-- <div>@item.ImageDescriptionShort</div>-->
                    <div style="font-weight:bold;color:black;font-size:14px;">@item.Price.ToString("c")</div>
                </a>
            </td>
        }
    </tr>
</table>